/*
 * Generated by
 *
 *	  _   _ _ __  _ __   _____  _| |_    __ _  ___ _ __   ___ _ __ __ _| |_ ___  _ __
 *	 | | | | '_ \| '_ \ / _ \ \/ / __|  / _` |/ _ \ '_ \ / _ \ '__/ _` | __/ _ \| '__|
 *	 | |_| | | | | | | |  __/>  <| |_  | (_| |  __/ | | |  __/ | | (_| | || (_) | |
 *	  \__,_|_| |_|_| |_|\___/_/\_\\__|  \__, |\___|_| |_|\___|_|  \__,_|\__\___/|_|
 *									                    |___/
 *
 *
 * The yeoman generator that generates code for NextJS applications
 *
 *	http://boxfusion.co.za
 *
 */

// F => Failure
// I => Inprogress
// S => Success
// A => Actioned

//#region Flags
export const FETCH_POSTS_REQUEST__F__FISA = 'FETCH_POSTS_REQUEST__F__IFSA';

export const FETCH_POSTS_SUCCESS__F__FISA = 'FETCH_POSTS_SUCCESS__F__FISA';

export const FETCH_POSTS_ERROR__F__FISA = 'FETCH_POSTS_ERROR__F__FISA';
//#endregion
