//#region Flags
export const FETCH_POSTS_REQUEST__F__FISA = 'FETCH_POSTS_REQUEST__F__IFSA';

export const FETCH_POSTS_SUCCESS__F__FISA = 'FETCH_POSTS_SUCCESS__F__FISA';

export const FETCH_POSTS_ERROR__F__FISA = 'FETCH_POSTS_ERROR__F__FISA';
